import React, { createContext, useContext, useState } from 'react';

const translations = {
  th: {
    brand: "Vertical Project",
    tagline: "พื้นที่แห่งความผ่อนคลาย",
    home: "หน้าแรก",
    bookNow: "จองคิว",
    selectService: "เลือกทรีตเมนต์",
    selectTherapist: "เลือกผู้เชี่ยวชาญ",
    selectDateTime: "เลือกวันและเวลา",
    confirmBooking: "ยืนยันการจอง",
    payment: "ชำระเงิน",
    bookingHistory: "ประวัติการจอง",
    profile: "โปรไฟล์",
    services: "บริการ",
    popular: "ยอดนิยม",
    all: "ทั้งหมด",
    massage: "นวด",
    facial: "ดูแลผิวหน้า",
    body_treatment: "ทรีตเมนต์ผิวกาย",
    package: "แพ็คเกจ",
    wellness: "เวลเนส",
    minutes: "นาที",
    thb: "บาท",
    noPreference: "ไม่ระบุ (ให้ร้านจัด)",
    anyTherapist: "ผู้เชี่ยวชาญท่านใดก็ได้",
    selectDate: "เลือกวันที่",
    availableSlots: "เวลาว่าง",
    noSlots: "ไม่มีเวลาว่างในวันนี้",
    bookingSummary: "สรุปการจอง",
    service: "บริการ",
    therapist: "ผู้เชี่ยวชาญ",
    date: "วันที่",
    time: "เวลา",
    duration: "ระยะเวลา",
    total: "รวมทั้งสิ้น",
    promptpay: "พร้อมเพย์ QR",
    bank_transfer: "โอนผ่านธนาคาร",
    truemoney: "TrueMoney Wallet",
    rabbit_line_pay: "Rabbit LINE Pay",
    credit_card: "บัตรเครดิต / เดบิต",
    cash: "ชำระที่ร้าน",
    paymentMethod: "เลือกวิธีชำระเงิน",
    scanQR: "สแกน QR เพื่อชำระเงิน",
    paymentPending: "รอการชำระเงิน",
    paymentConfirmed: "ชำระเงินเรียบร้อย",
    bookingConfirmed: "จองสำเร็จ!",
    bookingPending: "รอการยืนยัน",
    backToHome: "กลับหน้าแรก",
    viewBookings: "ดูการจองของฉัน",
    today: "วันนี้",
    upcoming: "กำลังจะมาถึง",
    past: "ผ่านมาแล้ว",
    cancelled: "ยกเลิก",
    status: "สถานะ",
    pending: "รอยืนยัน",
    confirmed: "ยืนยันแล้ว",
    checked_in: "เช็คอินแล้ว",
    in_progress: "กำลังดำเนินการ",
    completed: "เสร็จสิ้น",
    no_show: "ไม่มาตามนัด",
    cancel: "ยกเลิก",
    reschedule: "เปลี่ยนเวลา",
    review: "รีวิว",
    staffDashboard: "แผงควบคุมพนักงาน",
    adminDashboard: "แผงควบคุมผู้ดูแล",
    schedule: "ตารางนัดหมาย",
    clients: "ลูกค้า",
    reports: "รายงาน",
    settings: "ตั้งค่า",
    checkIn: "เช็คอิน",
    checkOut: "เช็คเอาท์",
    noBookings: "ยังไม่มีการจอง",
    loginWithLine: "เข้าสู่ระบบด้วย LINE",
    welcome: "ยินดีต้อนรับ",
    upcoming: "กำลังจะมาถึง",
    promotions: "โปรโมชั่น",
    loyalty: "คะแนนสะสม",
    points: "คะแนน",
    membership: "สมาชิก",
    search: "ค้นหา",
    filter: "กรอง",
    sort: "เรียง",
    next: "ถัดไป",
    back: "กลับ",
    confirm: "ยืนยัน",
    close: "ปิด",
    save: "บันทึก",
    edit: "แก้ไข",
    delete: "ลบ",
    add: "เพิ่ม",
    export: "ส่งออก",
    scheduleBoard: "ตารางงาน (D&D)",
    dailyView: "รายวัน",
    weeklyView: "รายสัปดาห์",
    revenue: "รายได้",
    bookings: "การจอง",
    customers: "ลูกค้า",
    staffNotes: "บันทึกพนักงาน",
    paid: "ชำระแล้ว",
    unpaid: "ยังไม่ชำระ",
    refunded: "คืนเงินแล้ว",
  },
  en: {
    brand: "Vertical Project",
    tagline: "Your Space of Serenity",
    home: "Home",
    bookNow: "Book Now",
    selectService: "Select Treatment",
    selectTherapist: "Select Therapist",
    selectDateTime: "Select Date & Time",
    confirmBooking: "Confirm Booking",
    payment: "Payment",
    bookingHistory: "Booking History",
    profile: "Profile",
    services: "Services",
    popular: "Popular",
    all: "All",
    massage: "Massage",
    facial: "Facial",
    body_treatment: "Body Treatment",
    package: "Package",
    wellness: "Wellness",
    minutes: "min",
    thb: "THB",
    noPreference: "No Preference",
    anyTherapist: "Any Available Therapist",
    selectDate: "Select Date",
    availableSlots: "Available Slots",
    noSlots: "No available slots for this day",
    bookingSummary: "Booking Summary",
    service: "Service",
    therapist: "Therapist",
    date: "Date",
    time: "Time",
    duration: "Duration",
    total: "Total",
    promptpay: "PromptPay QR",
    bank_transfer: "Bank Transfer",
    truemoney: "TrueMoney Wallet",
    rabbit_line_pay: "Rabbit LINE Pay",
    credit_card: "Credit / Debit Card",
    cash: "Pay at Spa",
    paymentMethod: "Select Payment Method",
    scanQR: "Scan QR to Pay",
    paymentPending: "Payment Pending",
    paymentConfirmed: "Payment Confirmed",
    bookingConfirmed: "Booking Confirmed!",
    bookingPending: "Pending Confirmation",
    backToHome: "Back to Home",
    viewBookings: "View My Bookings",
    today: "Today",
    upcoming: "Upcoming",
    past: "Past",
    cancelled: "Cancelled",
    status: "Status",
    pending: "Pending",
    confirmed: "Confirmed",
    checked_in: "Checked In",
    in_progress: "In Progress",
    completed: "Completed",
    no_show: "No Show",
    cancel: "Cancel",
    reschedule: "Reschedule",
    review: "Review",
    staffDashboard: "Staff Dashboard",
    adminDashboard: "Admin Dashboard",
    schedule: "Schedule",
    clients: "Clients",
    reports: "Reports",
    settings: "Settings",
    checkIn: "Check In",
    checkOut: "Check Out",
    noBookings: "No bookings yet",
    loginWithLine: "Login with LINE",
    welcome: "Welcome",
    promotions: "Promotions",
    loyalty: "Loyalty Points",
    points: "pts",
    membership: "Membership",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    next: "Next",
    back: "Back",
    confirm: "Confirm",
    close: "Close",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    export: "Export",
    scheduleBoard: "Schedule Board",
    dailyView: "Daily",
    weeklyView: "Weekly",
    revenue: "Revenue",
    bookings: "Bookings",
    customers: "Customers",
    staffNotes: "Staff Notes",
    paid: "Paid",
    unpaid: "Unpaid",
    refunded: "Refunded",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('th');
  const t = (key) => translations[lang]?.[key] || translations['en']?.[key] || key;
  const toggleLang = () => setLang(l => l === 'th' ? 'en' : 'th');
  
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}